### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by abdallah-moh** [rhyme-project/rhyme#136]
## To-do
- [ ] Add a command palette
- [ ] Have community themes available
- [ ] Finish website
- [ ] Artists Tab
- [ ] Another sidebar for interacting with currently playing album `It will hide if no albums are playing `
